---
title: "tsi_1984-2021"
author: "Shawn Schneidereit"
date: "`r Sys.Date()`"
output: 
  html_document:
   fig_width: 10
   fig_height: 6
   toc: TRUE
   toc_float: TRUE
   toc_collapsed: FALSE
   code_folding: hide
   theme: united
   highlight: tango


---

```{r, cache=TRUE, setup, include=FALSE}
# library
library(terra)     # raster data maipulations
#library(sf)
library(viridis)   # color palletes
library(tidyverse) # data manipulation
library(patchwork) # for grid visualization
library(ggridges)  # ridge plots
library(ggpmisc)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```


## test visualizazion of recompiled GreenLand masks

```{r, chache=TRUE}


link <- "/data/Dagobah/greengrass/grassland_ger/01_CTM_GL_mask_17-19/GL_mask_2017-2019.tif"

mask_GL <- rast(link)

plot(mask_GL)

```


# test vis for tsi output

# plot raw images
```{r, cache=TRUE, eval=TRUE}

link <- "/data/Dagobah/greengrass/schnesha/03_RBF_interpolation_LND_1982-2021/X0060_Y0040/1984-2021_001-365_HL_TSA_LNDLG_NDV_TSI.tif"

tsi_raw <- rast(link)
plot(tsi_raw[[c(5:15)]])

# apply GL mask to time series interpolation
common.extent <- intersect(tsi_raw, mask_GL)
tsi_raw <- crop(tsi_raw, common.extent)
mask_GL <- crop(mask_GL, common.extent)
tsi <- mask(tsi_raw, mask_GL)




tsi_df <- as.data.frame(tsi[[c(4:24)]], xy = TRUE)

tsi_df_long <- tsi_df |> 
  pivot_longer(cols = c(3:ncol(tsi_df)), names_to = "timestamp") |> 
  slice_sample(n=10000) |> 
  mutate(xy= paste0(x,"_",y))

ggplot(tsi_df_long, aes(timestamp, value, group=xy)) +
  geom_line() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45)) 

ggplot(na.omit(tsi_df_long), aes(timestamp, value)) +
  geom_smooth() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45)) 

ggplot(tsi_df_long, aes(timestamp, value, group = timestamp)) +
  geom_boxplot() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) 

```

# save images and construct gif
```{r, cache=TRUE, eval=FALSE}

for (i in c(1:#length(names(tsi))
            10)) {
  
  # Step 1: Call the pdf command to start the plot
  png(file = paste0("/data/Dagobah/greengrass/schnesha/03_RBF_interpolation_LND_1982-2021/ts_gif/plot_", i, ".png")) #,   # The directory you want to save the file in
   # width = 12, # The width of the plot in inches
    #height = 12) # The height of the plot in inches
plot(tsi[[i]])

# Step 3: Run dev.off() to create the file
dev.off()

}

```






































































